title: Jose Quan 
logo: "/images/MLpic.PNG?raw=true" 
description: This is an MSBA containing assignments, projects, and presentations. 

   <br><br>
   <a href="https://www.linkedin.com/in/josecquan/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

